export const testJson={
    "Customers":"Religious people seeking guidance and answers from scriptures",
    "Brand Message":"Providing solutions to life problems through religious scriptures",
    "Offerings":"Access to personalized scriptural guidance and responses to individual questions",
    "Processes":"Scriptural research, analysis, and interpretation to provide accurate responses",
    "R&D Partner":"Religious scholars and experts",
    "Jobs to be Done":"Helping religious people find guidance and answers to life problems through scriptural teachings",
    "Pains":"Lack of clear answers and guidance from religious institutions or leaders",
    "Core Values":"Spiritual growth, understanding, and fulfillment through scriptural guidance",
    "Gains":"Clear answers and guidance on life problems through scriptural teachings",
    "Operating Partner":"Technology platforms for delivering and managing scriptural responses",
    "Unfair Advantage":"Expertise in scriptural research and analysis, and personalized guidance tailored to individual needs",
    "Channels":"Online platforms and social media",
    "Resources":"Scriptural texts and research materials, technology infrastructure",
    "Users":"Religious people seeking guidance and answers from scriptural teachings",
    "Costs":"Research and technology costs, operational costs for managing the platform",
    "Pricing":"Fee-based subscription model for personalized scriptural guidance",
    "Investments":"Initial investment in research, development, and technology infrastructure"}
